# Generated by Django 2.0.9 on 2020-09-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Nacionalidad', models.CharField(max_length=30)),
                ('Rut', models.CharField(max_length=13)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Departamento', models.CharField(max_length=30)),
                ('habitaciones', models.IntegerField()),
                ('Baños', models.IntegerField()),
                ('Calefaccion', models.CharField(max_length=2)),
                ('Internet', models.CharField(max_length=2)),
                ('Amobla', models.CharField(max_length=2)),
                ('Televición', models.CharField(max_length=2)),
                ('Imagen_Recinto', models.ImageField(upload_to='')),
                ('Imagen_Entorno', models.ImageField(upload_to='')),
                ('Valor_Diario', models.IntegerField()),
                ('Disponible', models.CharField(max_length=2)),
            ],
        ),
    ]
