# Generated by Django 2.0.9 on 2020-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Reserva_Inicio', models.DateField()),
                ('Fecha_Reserva_Termino', models.DateField()),
            ],
        ),
    ]
