# Generated by Django 2.0.9 on 2020-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0003_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Nacionalidad', models.CharField(max_length=30)),
                ('Rut', models.CharField(max_length=13)),
                ('DV', models.CharField(max_length=1)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
