# Generated by Django 2.2.5 on 2020-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0004_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Servicio', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tur_Descripcion_Servicio', models.CharField(default='', max_length=200)),
                ('Tur_Fecha', models.DateField(default='')),
                ('Tur_Valor', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='Amobla',
            new_name='Amoblado',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='Costo',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Check_in',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Check_out',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Numero_propiedad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Estado_Reserva',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Tipo_Vehiculo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Trans_Costo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Trans_Descripcion',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Trans_Destino',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Trans_Fecha',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='transporte',
            name='Trans_Recogida',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Baños',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='habitaciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Inicio',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Termino',
            field=models.DateField(default=''),
        ),
    ]
