# Generated by Django 2.0.9 on 2020-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0004_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
