# Generated by Django 2.0.9 on 2020-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0005_clientes_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='Check_in',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='Check_out',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='Descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='Direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='Numero_propiedad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
