# Generated by Django 2.2.5 on 2020-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0005_auto_20200929_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Inicio',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Termino',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='Trans_Fecha',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='Tur_Fecha',
            field=models.DateField(default='', null=True),
        ),
    ]
