# Generated by Django 2.0.9 on 2020-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0006_auto_20200914_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
