# Generated by Django 2.0.9 on 2020-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0007_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_Servicio', models.CharField(max_length=200)),
                ('Tipo', models.CharField(max_length=30)),
                ('Valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='transporte',
            name='Destino',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporte',
            name='Fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporte',
            name='Recogida',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporte',
            name='Tipo_Vehiculo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
