# Generated by Django 2.0.9 on 2020-09-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0008_auto_20200914_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio_Extra',
            new_name='ServicioExtra',
        ),
    ]
