# Generated by Django 2.0.9 on 2020-09-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTurismo', '0010_auto_20200914_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioExtra',
        ),
    ]
